version: "3.3"

services:
    mariadb:
      build: ./requirements/mariadb
      container_name: mariadb
      restart: always
      networks:
      - docker-network
      volumes:
      - vol_db:/var/lib/mysql/
      env_file: .env
    nginx:
      build: ./requirements/nginx/
      container_name: nginx
      depends_on:
       - wordpress
      ports:
       - 443:443
      restart: always
      networks:
       - docker-network
      volumes:
       - vol_wp:/var/www/
      extra_hosts:
        - ${DOMAIN_NAME}:127.0.0.1
    wordpress:
      build: ./requirements/wordpress/
      container_name: wordpress
      depends_on:
       - mariadb
      restart: always
      networks:
       - docker-network
      volumes:
       - vol_wp:/var/www/
      env_file: .env

networks:
  docker-network:

volumes:
    vol_db:
      driver: local
      driver_opts:
        type: "none"
        o: "bind"
        device: /home/${USER}/data/db
    vol_wp:
      driver: local
      driver_opts:
        type: "none"
        o: "bind"
        device: /home/${USER}/data/www