version: '3.9'

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - 443:443
    volumes:
      - www:/var/www/
    networks:
      - app

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file: .env
#    environment:
#      - WORDPRESS_DB_HOST=
#      - WORDPRESS_DB_USER=$MYSQL_USER
#      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
#      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - www:/var/www/
    networks:
      - app

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - app

volumes:
  www:
  db:

networks:
  app:
    driver: local