version: '3.3'

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - www-html:/var/www/$DOMAIN_NAME
    networks:
      - app

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - www-html:/var/www/$DOMAIN_NAME
    networks:
      - app

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - dbfile:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app

volumes:
  www-html:
  dbfile:

networks:
  app:
    driver: bridge
